### PR TITLE
Grim issue40 - Fix for LogDir typo in template

### PR DESCRIPTION
**Pull request by varun06**

### CODE REVIEW

**Comment by kklipsch** [comment]
this looks like it hasnt been merged correctly.  github at least is confused and showing previously merged changes with this change set.  I'd like to see that resovled before we push this.

**Comment by kklipsch** [comment]
Another side note.  In the future, if we encounter these kind of dependency management issues that require "fast" deployment that they be in their own pull request.  That will expedite getting them merged and allow people to work on top of that particular pull request without thinking through the ramifications of the other ones.

**Comment by varun06** [comment]
hmm, github snafu's, but at least it is passing now. Also I have moved the aws stuff to other PR.

**Comment by varun06** [comment]
This PR has too many unwanted changes merged, deleting it for now.

**Pull request closed without merging**
